a = input("Nhap a: ")
b = input("Nhap b: ")
print ("a+b=",int (a)+int(b))
print ("a+b=",int (a)-int(b))
print ("a*b=",int (a)*int(b))
print ("a/b=",float(a)/float(b))
print ("a%b=",float(a)%float(b))
print ("a**b=",float(a)**float(b))
